// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCh15biZTz0VSdR3Ua8ae_QCdRf4aZ68jU',
    appId: '1:1073948930027:web:332c977c8d438ed0a6b3ae',
    messagingSenderId: '1073948930027',
    projectId: 'coread-app',
    authDomain: 'coread-app.firebaseapp.com',
    storageBucket: 'coread-app.firebasestorage.app',
    measurementId: 'G-VMC59T36C7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1dER32XTsQaSCCM-aPDHpui7T9WMLGRs',
    appId: '1:1073948930027:android:5378c194439558e7a6b3ae',
    messagingSenderId: '1073948930027',
    projectId: 'coread-app',
    storageBucket: 'coread-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzo1tN-IQYRPXMRY73KtjS_WeE3Ojz0MY',
    appId: '1:1073948930027:ios:0bcadfcc7ce57f9ba6b3ae',
    messagingSenderId: '1073948930027',
    projectId: 'coread-app',
    storageBucket: 'coread-app.firebasestorage.app',
    iosBundleId: 'com.example.mangaapp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzo1tN-IQYRPXMRY73KtjS_WeE3Ojz0MY',
    appId: '1:1073948930027:ios:0bcadfcc7ce57f9ba6b3ae',
    messagingSenderId: '1073948930027',
    projectId: 'coread-app',
    storageBucket: 'coread-app.firebasestorage.app',
    iosBundleId: 'com.example.mangaapp1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCh15biZTz0VSdR3Ua8ae_QCdRf4aZ68jU',
    appId: '1:1073948930027:web:ddcd58a09769191aa6b3ae',
    messagingSenderId: '1073948930027',
    projectId: 'coread-app',
    authDomain: 'coread-app.firebaseapp.com',
    storageBucket: 'coread-app.firebasestorage.app',
    measurementId: 'G-74X3D9ZG0V',
  );
}
